---
label: Services
hide_body: true
fields:
- type: text
  name: title
  label: title
- type: text
  name: body
  label: body
- name: authors
  type: field_group_list
  config:
    min: 
    max: 
    labelField: 
  label: Authors
  description: List of authors goes here
